feat(plugin): register ts sub types (#486)

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -109,7 +109,7 @@ jobs:
       - name: Auto merge pull request
         continue-on-error: true
         if: steps.cpr.outputs.pull-request-operation == 'created'
-        run: gh pr merge ${{ env.PULL_REQUEST_NUMBER }} --squash --admin
+        run: gh pr merge ${{ env.PULL_REQUEST_NUMBER }} --squash --admin --verbose
         env:
           GH_TOKEN: ${{ secrets.ACTION_TOKEN }}
 
@@ -165,7 +165,7 @@ jobs:
       - name: Auto merge pull request
         continue-on-error: true
         if: steps.cpr.outputs.pull-request-operation == 'created'
-        run: gh pr merge ${{ env.PULL_REQUEST_NUMBER }} --squash --admin
+        run: gh pr merge ${{ env.PULL_REQUEST_NUMBER }} --squash --admin --verbose
         env:
           GH_TOKEN: ${{ secrets.ACTION_TOKEN }}
 
@@ -194,7 +194,12 @@ jobs:
 
       - name: Find release commit
         run: |
-          echo "release_commit=$(git log --grep="chore: release ${{ env.release_version }}" -n 10 --pretty=format:%H)" >> "${GITHUB_ENV}"
+          release_commit=$(git log --grep="chore: release ${{ env.release_version }}" -n 10 --pretty=format:%H)
+          if [ -z "$release_commit" ]; then
+            echo "Error: release_commit is empty or does not exist"
+            exit 1
+          fi
+          echo "release_commit=${release_commit}" >> "${GITHUB_ENV}"
 
       - name: Create release tag
         id: tag_version
@@ -240,7 +245,7 @@ jobs:
           java-version: 8
 
       - name: Build and publish
-        run: ./gradlew publish -Dorg.gradle.parallel=false
+        run: ./gradlew publish -Dorg.gradle.parallel=false --info
         env:
           GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
           GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
